export type Range = { min: number; max: number };

export type SectionConfig = {
  id: string;
  title: string;
  column: string;
  targetsByPosition: Record<string, Range>;
  lowAction: string;
  highAction: string;
  goodAction: string;
};

export const SECTIONS: SectionConfig[] = [
  {
    id: "raise-first",
    title: "Raise First",
    column: "Raise First",
    targetsByPosition: {
      SB: { min: 25, max: 30 },
      EP: { min: 16, max: 20 },
      MP: { min: 24, max: 27 },
      CO: { min: 35, max: 38 },
      BTN: { min: 47, max: 55 },
    },
    lowAction: "Raise more",
    highAction: "Raise less",
    goodAction: "Good job",
  },
  {
    id: "limp-open",
    title: "Limp Open",
    column: "Limp Open",
    targetsByPosition: { SB: { min: 55, max: 65 } },
    lowAction: "Limp more",
    highAction: "Limp less",
    goodAction: "Good job",
  },
  {
    id: "limp-raise",
    title: "Limp/Raise",
    column: "Limp/Raise",
    targetsByPosition: { SB: { min: 10, max: 14 } },
    lowAction: "Raise more",
    highAction: "Raise less",
    goodAction: "Good job",
  },
  {
    id: "limp-call",
    title: "Limp/Call",
    column: "Limp/Call",
    targetsByPosition: { SB: { min: 45, max: 55 } },
    lowAction: "Call more",
    highAction: "Call less",
    goodAction: "Good job",
  },
  {
    id: "limp-fold",
    title: "Limp/Fold",
    column: "Limp/Fold",
    targetsByPosition: { SB: { min: 35, max: 45 } },
    lowAction: "Fold more",
    highAction: "Fold less",
    goodAction: "Good job",
  },
  {
    id: "raise-sb-open-limp",
    title: "Raise SB Open Limp",
    column: "Raise SB Open Limp",
    targetsByPosition: { BB: { min: 40, max: 45 } },
    lowAction: "Raise more",
    highAction: "Raise less",
    goodAction: "Good job",
  },
  {
    id: "fold-bb-v-sb",
    title: "Fold BB v SB",
    column: "Fold BB v SB",
    targetsByPosition: { BB: { min: 35, max: 45 } },
    lowAction: "Fold more",
    highAction: "Fold less",
    goodAction: "Good job",
  },
  {
    id: "fold-to-steal",
    title: "Fold to Steal",
    column: "Fold to Steal",
    targetsByPosition: {
      SB: { min: 70, max: 75 },
      BB: { min: 30, max: 35 },
    },
    lowAction: "Fold more",
    highAction: "Fold less",
    goodAction: "Good job",
  },
  {
    id: "call-pf-2bet",
    title: "Call PF 2Bet",
    column: "Call PF 2Bet",
    targetsByPosition: {
      SB: { min: 10, max: 14 },
      BB: { min: 45, max: 55 },
      EP: { min: 3, max: 6 },
      MP: { min: 4, max: 7 },
      CO: { min: 6, max: 9 },
      BTN: { min: 9, max: 13 },
    },
    lowAction: "Call more",
    highAction: "Call less",
    goodAction: "Good job",
  },
  {
    id: "3bet-pf",
    title: "3Bet PF",
    column: "3Bet PF",
    targetsByPosition: {
      SB: { min: 10, max: 14 },
      BB: { min: 9, max: 13 },
      EP: { min: 5, max: 7 },
      MP: { min: 6, max: 8 },
      CO: { min: 7, max: 10 },
      BTN: { min: 8, max: 12 },
    },
    lowAction: "3-bet more",
    highAction: "3-bet less",
    goodAction: "Good job",
  },
  {
    id: "3bet-steal",
    title: "3Bet Steal",
    column: "3Bet Steal",
    targetsByPosition: {
      SB: { min: 16, max: 19 },
      BB: { min: 16, max: 19 },
    },
    lowAction: "3-bet steal more",
    highAction: "3-bet steal less",
    goodAction: "Good job",
  },
  {
    id: "3bet-nai-lt35",
    title: "3Bet NAI <35",
    column: "3Bet NAI <35",
    targetsByPosition: {
      SB: { min: 5, max: 8 },
      BB: { min: 5, max: 8 },
      EP: { min: 3, max: 6 },
      MP: { min: 3, max: 6 },
      CO: { min: 3, max: 6 },
      BTN: { min: 3, max: 6 },
    },
    lowAction: "3-bet more",
    highAction: "3-bet less",
    goodAction: "Good job",
  },
  {
    id: "2bet-pf-fold",
    title: "2Bet PF & Fold",
    column: "2Bet PF & Fold",
    targetsByPosition: {
      SB: { min: 45, max: 55 },
      BB: { min: 45, max: 55 },
      EP: { min: 45, max: 55 },
      MP: { min: 45, max: 55 },
      CO: { min: 47, max: 55 },
      BTN: { min: 50, max: 57 },
    },
    lowAction: "Fold more",
    highAction: "Fold less",
    goodAction: "Good job",
  },
  {
    id: "raise-4betplus-pf",
    title: "Raise & 4Bet+ PF",
    column: "Raise & 4Bet+ PF ",
    targetsByPosition: {
      SB: { min: 12, max: 18 },
      EP: { min: 15, max: 20 },
      MP: { min: 15, max: 20 },
      CO: { min: 12, max: 18 },
      BTN: { min: 12, max: 18 },
    },
    lowAction: "4-bet more",
    highAction: "4-bet less",
    goodAction: "Good job",
  },
  {
    id: "3bet-pf-fold",
    title: "3Bet PF & Fold",
    column: "3Bet PF & Fold",
    targetsByPosition: {
      SB: { min: 40, max: 50 },
      BB: { min: 40, max: 50 },
      EP: { min: 40, max: 50 },
      MP: { min: 40, max: 50 },
      CO: { min: 40, max: 50 },
      BTN: { min: 40, max: 50 },
    },
    lowAction: "Fold more",
    highAction: "Fold less",
    goodAction: "Good job",
  },
  {
    id: "fold-to-pf-4bet-after-3bet-lt30",
    title: "Fold to PF 4Bet After 3Bet <30",
    column: "Fold to PF 4Bet After 3Bet <30 ",
    targetsByPosition: {
      SB: { min: 35, max: 45 },
      BB: { min: 35, max: 45 },
      EP: { min: 35, max: 45 },
      MP: { min: 35, max: 45 },
      CO: { min: 35, max: 45 },
      BTN: { min: 35, max: 45 },
    },
    lowAction: "Fold more",
    highAction: "Fold less",
    goodAction: "Good job",
  },
  {
    id: "pf-squeeze",
    title: "PF Squeeze",
    column: "PF Squeeze",
    targetsByPosition: {
      SB: { min: 7, max: 11 },
      BB: { min: 9, max: 15 },
      MP: { min: 5, max: 7 },
      CO: { min: 6, max: 9 },
      BTN: { min: 8, max: 12 },
    },
    lowAction: "Squeeze more",
    highAction: "Squeeze less",
    goodAction: "Good job",
  },
  {
    id: "cbet-f-oop-hu",
    title: "CBet F OOP (HU)",
    column: "CBet F OOP (HU)",
    targetsByPosition: {
      SB: { min: 60, max: 75 },
      BB: { min: 70, max: 85 },
      EP: { min: 35, max: 45 },
      MP: { min: 30, max: 40 },
      CO: { min: 25, max: 30 },
    },
    lowAction: "Bet more",
    highAction: "Bet less",
    goodAction: "Good job",
  },
  {
    id: "cbet-f-ip-hu",
    title: "CBet F IP (HU)",
    column: "CBet F IP (HU)",
    targetsByPosition: {
      BB: { min: 55, max: 65 },
      EP: { min: 80, max: 90 },
      MP: { min: 75, max: 85 },
      CO: { min: 75, max: 85 },
      BTN: { min: 70, max: 80 },
    },
    lowAction: "Bet more",
    highAction: "Bet less",
    goodAction: "Good job",
  },
  {
    id: "float-f-hu",
    title: "Float F HU",
    column: "Float F HU",
    targetsByPosition: {
      BB: { min: 40, max: 50 },
      EP: { min: 45, max: 55 },
      MP: { min: 45, max: 55 },
      CO: { min: 45, max: 55 },
      BTN: { min: 45, max: 55 },
    },
    lowAction: "Bet more",
    highAction: "Bet less",
    goodAction: "Good job",
  },
  {
    id: "fold-to-f-cbet-hu",
    title: "Fold to F Cbet (HU)",
    column: "Fold to F Cbet (HU)",
    targetsByPosition: {
      SB: { min: 33, max: 38 },
      BB: { min: 40, max: 45 },
      EP: { min: 33, max: 38 },
      MP: { min: 33, max: 38 },
      CO: { min: 28, max: 35 },
      BTN: { min: 27, max: 33 },
    },
    lowAction: "Fold more",
    highAction: "Fold less",
    goodAction: "Good job",
  },
  {
    id: "fold-to-f-cbet-3b",
    title: "Fold to F CBet (3B)",
    column: "Fold to F CBet (3B)",
    targetsByPosition: {
      SB: { min: 30, max: 40 },
      EP: { min: 35, max: 45 },
      MP: { min: 35, max: 45 },
      CO: { min: 30, max: 35 },
      BTN: { min: 30, max: 35 },
    },
    lowAction: "Fold more",
    highAction: "Fold less",
    goodAction: "Good job",
  },
  {
    id: "fold-to-f-float-hu",
    title: "Fold to F Float HU",
    column: "Fold to F Float HU",
    targetsByPosition: {
      SB: { min: 25, max: 35 },
      EP: { min: 30, max: 40 },
      MP: { min: 30, max: 40 },
      CO: { min: 30, max: 40 },
    },
    lowAction: "Fold more",
    highAction: "Fold less",
    goodAction: "Good job",
  },
  {
    id: "cbet-f-fold-hu",
    title: "CBet F & Fold (HU)",
    column: "CBet F & Fold (HU)",
    targetsByPosition: {
      SB: { min: 33, max: 43 },
      BB: { min: 33, max: 43 },
      EP: { min: 33, max: 43 },
      MP: { min: 33, max: 43 },
      CO: { min: 33, max: 43 },
      BTN: { min: 33, max: 43 },
    },
    lowAction: "Fold more",
    highAction: "Fold less",
    goodAction: "Good job",
  },
  {
    id: "raise-f-cbet-hu",
    title: "Raise F CBet (HU)",
    column: "Raise F CBet (HU)",
    targetsByPosition: {
      SB: { min: 16, max: 20 },
      BB: { min: 16, max: 20 },
      EP: { min: 14, max: 18 },
      MP: { min: 14, max: 18 },
      CO: { min: 12, max: 18 },
      BTN: { min: 7, max: 10 },
    },
    lowAction: "Raise more",
    highAction: "Raise less",
    goodAction: "Good job",
  },
  {
    id: "xr-flop-hu",
    title: "XR Flop HU",
    column: "XR Flop HU",
    targetsByPosition: {
      SB: { min: 16, max: 20 },
      BB: { min: 16, max: 20 },
      EP: { min: 16, max: 20 },
      MP: { min: 16, max: 20 },
      CO: { min: 16, max: 20 },
    },
    lowAction: "Raise more",
    highAction: "Raise less",
    goodAction: "Good job",
  },
  {
    id: "raise-f-cbet-3b",
    title: "Raise F CBet (3B)",
    column: "Raise F CBet (3B)",
    targetsByPosition: {
      SB: { min: 15, max: 19 },
      EP: { min: 12, max: 18 },
      MP: { min: 12, max: 18 },
      CO: { min: 8, max: 14 },
      BTN: { min: 6, max: 10 },
    },
    lowAction: "Raise more",
    highAction: "Raise less",
    goodAction: "Good job",
  },
  {
    id: "donk-t-hu",
    title: "Donk T (HU)",
    column: "Donk T (HU)",
    targetsByPosition: {
      SB: { min: 5, max: 8 },
      BB: { min: 7, max: 11 },
      EP: { min: 5, max: 7 },
      MP: { min: 5, max: 7 },
      CO: { min: 4, max: 6 },
    },
    lowAction: "Donk more",
    highAction: "Donk less",
    goodAction: "Good job",
  },
  {
    id: "cbet-t-hu",
    title: "CBet T (HU)",
    column: "CBet T (HU)",
    targetsByPosition: {
      SB: { min: 47, max: 57 },
      BB: { min: 47, max: 57 },
      EP: { min: 47, max: 57 },
      MP: { min: 47, max: 57 },
      CO: { min: 47, max: 57 },
      BTN: { min: 47, max: 57 },
    },
    lowAction: "Bet more",
    highAction: "Bet less",
    goodAction: "Good job",
  },
  {
    id: "float-t",
    title: "Float T",
    column: "Float T",
    targetsByPosition: {
      BB: { min: 45, max: 55 },
      EP: { min: 45, max: 55 },
      MP: { min: 45, max: 55 },
      CO: { min: 45, max: 55 },
      BTN: { min: 45, max: 55 },
    },
    lowAction: "Bet more",
    highAction: "Bet less",
    goodAction: "Good job",
  },
  {
    id: "probe-t-hu",
    title: "Probe T (HU)",
    column: "Probe T (HU)",
    targetsByPosition: {
      SB: { min: 35, max: 45 },
      BB: { min: 35, max: 45 },
      EP: { min: 35, max: 45 },
      MP: { min: 35, max: 45 },
      CO: { min: 35, max: 45 },
    },
    lowAction: "Bet more",
    highAction: "Bet less",
    goodAction: "Good job",
  },
  {
    id: "probe-t-hu-bet-r",
    title: "Probe T HU & Bet R",
    column: "Probe T HU & Bet R",
    targetsByPosition: {
      SB: { min: 55, max: 65 },
      BB: { min: 55, max: 65 },
    },
    lowAction: "Bet more",
    highAction: "Bet less",
    goodAction: "Good job",
  },
  {
    id: "fold-to-t-cbet",
    title: "Fold to T CBet",
    column: "Fold to T CBet",
    targetsByPosition: {
      SB: { min: 35, max: 45 },
      BB: { min: 35, max: 45 },
      EP: { min: 35, max: 45 },
      MP: { min: 35, max: 45 },
      CO: { min: 33, max: 43 },
      BTN: { min: 33, max: 43 },
    },
    lowAction: "Fold more",
    highAction: "Fold less",
    goodAction: "Good job",
  },
  {
    id: "f-to-t-pr-hu",
    title: "F to T Pr (HU)",
    column: "F to T Pr (HU)",
    targetsByPosition: {
      BB: { min: 30, max: 40 },
      EP: { min: 30, max: 40 },
      MP: { min: 30, max: 40 },
      CO: { min: 30, max: 40 },
      BTN: { min: 30, max: 40 },
    },
    lowAction: "Fold more",
    highAction: "Fold less",
    goodAction: "Good job",
  },
  {
    id: "raise-t-cbet",
    title: "Raise T CBet",
    column: "Raise T CBet",
    targetsByPosition: {
      SB: { min: 7, max: 10 },
      BB: { min: 7, max: 10 },
      EP: { min: 7, max: 10 },
      MP: { min: 7, max: 10 },
      CO: { min: 7, max: 10 },
      BTN: { min: 7, max: 10 },
    },
    lowAction: "Raise more",
    highAction: "Raise less",
    goodAction: "Good job",
  },
  {
    id: "raise-t-probe-hu",
    title: "Raise T Probe (HU)",
    column: "Raise T Probe (HU)",
    targetsByPosition: {
      BB: { min: 7, max: 10 },
      EP: { min: 7, max: 10 },
      MP: { min: 7, max: 10 },
      CO: { min: 7, max: 10 },
      BTN: { min: 7, max: 10 },
    },
    lowAction: "Raise more",
    highAction: "Raise less",
    goodAction: "Good job",
  },
  {
    id: "donk-r",
    title: "Donk R",
    column: "Donk R",
    targetsByPosition: {
      SB: { min: 6, max: 9 },
      BB: { min: 6, max: 9 },
      EP: { min: 6, max: 9 },
      MP: { min: 6, max: 9 },
      CO: { min: 6, max: 9 },
    },
    lowAction: "Donk more",
    highAction: "Donk less",
    goodAction: "Good job",
  },
  {
    id: "cbet-r",
    title: "CBet R",
    column: "CBet R",
    targetsByPosition: {
      SB: { min: 47, max: 57 },
      BB: { min: 47, max: 57 },
      EP: { min: 47, max: 57 },
      MP: { min: 47, max: 57 },
      CO: { min: 47, max: 57 },
      BTN: { min: 47, max: 57 },
    },
    lowAction: "Bet more",
    highAction: "Bet less",
    goodAction: "Good job",
  },
  {
    id: "fold-to-r-cbet",
    title: "Fold to R CBet",
    column: "Fold to R CBet",
    targetsByPosition: {
      SB: { min: 40, max: 50 },
      BB: { min: 40, max: 50 },
      EP: { min: 40, max: 50 },
      MP: { min: 40, max: 50 },
      CO: { min: 40, max: 50 },
      BTN: { min: 40, max: 50 },
    },
    lowAction: "Fold more",
    highAction: "Fold less",
    goodAction: "Good job",
  },
];
